<?php

$title = 'Login';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php if(!empty($displayMessage)) {
    echo '<h2>' . $displayMessage . '</h2>';
} ?>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('login', array('action' => 'process')));
$form->prepare();


echo $this->form()->openTag($form);

echo $this->formRow($form->get('username'));
echo $this->formRow($form->get('password'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

?>