<?php

$title = 'Login';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('login', array('action' => 'process')));
$form->prepare();

echo '<h3>' . $form->getAuthenticationMessage() . '</h3>';

echo $this->form()->openTag($form);

echo $this->formRow($form->get('username'));
echo $this->formRow($form->get('password'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

?>