<?php

$title = 'Delete City';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($city->name); ?>' from
    '<?php echo $this->escapeHtml($country->name); ?>'?
</p>
<?php
$url = $this->url('country', array(
    'action' => 'delete-city',
    'code'     => $this->code,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="code" value="<?php echo (String) $country->code; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>